server:
  port: 10000
  ssl:
    key-store: classpath:sample.jks
    key-store-password: secret
    key-password : password

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:1111/eureka/