server:
  port: 8888
  ssl:
    key-store: classpath:sample.jks
    key-store-password: secret
    key-password : password

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:1111/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iafboy/microservice_cloud_demo-config